const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS'
const REGISTER_FAIL = 'AUTH/REGISTER_FAIL'
const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS'
const LOGIN_FAIL = 'AUTH/LOGIN_FAIL'
const LOGOUT_SUCCESS = 'AUTH/LOGOUT_SUCCESS'
const AUTH_ERROR = 'AUTH/AUTH_ERROR'
const USER_LOADING = 'AUTH/USER_LOADING'
const USER_LOADED = 'AUTH/USER_LOADED'
const GET_ERRORS = 'GET_ERRORS'
const CLEAR_ERRORS = 'CLEAR_ERRORS'
const TASKS_LOADING = 'USER/TASKS_LOADING'
const TASKS_LOADED = 'USER/TASKS_LOADED'
const TASKS_FAIL = 'USER/TASKS_FAIL'

export {
	REGISTER_SUCCESS,
	REGISTER_FAIL,
	LOGOUT_SUCCESS,
	LOGIN_SUCCESS,
	LOGIN_FAIL,
	USER_LOADING,
	USER_LOADED,
	GET_ERRORS,
	CLEAR_ERRORS,
	AUTH_ERROR,
	TASKS_LOADING,
	TASKS_LOADED,
	TASKS_FAIL
}
